src/MomentLocale.php
The README.md file says the minimum PHP version must be 5.3
but this version doesn't support the square brackets syntax.
=> Use array() syntax.

src/Locales/en_US.php, src/Moment.php, tests/src/Moment/MomentTest.php
Fix for #47: The `getPeriod()` method does not take in to account the locale when finding the start and end of a week. This change pulls in the locale setting and considers it in the calculation. This also adds a unit test for Monday and Sunday start days.
=> Use locale day of week in getPeriod("week")

README.md
According to the ISO 3166-1 alpha-2 codes, `pt_BR` represents the Portuguese language spoken in
Brazil. The one for Portugal is `pt_PT`.
=> Fix README reference to pt_BR locale

src/Locales/ja_JP.php
I have made a translation for Japanese as your request in here.
https://github.com/fightbulc/moment.php/issues/62
I've done few tests on this, and it works fine.
Could you merge this changes?
Thanks.
=> Added japanese translation.

README.md, src/Moment.php, tests/unit/Moment/MomentTest.php
In response to #28, here is a PR that adds Immutable Mode!  When enabled, any modifications will first trigger a clone, and then the actual modifications will be performed on the clone instead of the origin.  It is possible to turn Immutable Mode on or off as needed, so you can temporarily unlock an object to make changes directly to it, then lock it again afterward.  A test has been added to verify that Immutable Mode does, in fact, make clones when changes are made, and that it can be toggled on and off after the object is constructed.  The README was also updated to reflect the new usage.
Signed-off-by: Daniel Hunsaker <danhunsaker@gmail.com>
=> Added Immutable Mode; updated README and added test

src/Locales/fr_FR.php, src/Moment.php, src/MomentLocale.php, tests/test.html, tests/test.php
Because custom formats (L, LL...) may depend on locale, add custom formats on locale files and merge them automatically if exist for the current locale value.
=> Localized custom formats

src/CustomFormats/MomentJs.php
Small typo in the date format of the 'LLL' moment locale formats.
Should be 'F jS Y g:i A'
=> Fix format of 'LLL' in Custom Formats

src/Locales/hu_HU.php
The weekdays for the hu_HU locale were in an incorrect order (sunday to saturday, insteaf of monday to sunday), making the translations incorrect. This is now fixed.
=> Updated incorrect order of weekdays for hu_HU locale

composer.json, tests/unit/Moment/MomentFrenchLocaleTest.php, tests/unit/Moment/MomentGermanLocaleTest.php, tests/unit/Moment/MomentPolishLocaleTest.php, tests/unit/Moment/MomentRussianLocaleTest.php, tests/unit/Moment/MomentTest.php, tests/unit/Moment/MomentTurkishLocaleTest.php, tests/unit/Moment/MomentUkrainianLocaleTest.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`^4.8.36`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md), that support this namespace.
=> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

src/Locales/lv_LV.php, tests/unit/Moment/MomentLatvianLocaleTest.php
Greetings
Grammatical corrections in context
- Moths names
- Relative time
- Calendar names
Updated unit tests
=> Fix grammar context of Latvian locale

src/CustomFormats/MomentJs.php, src/Locales/nl_NL.php
The `LTS` format (local time with seconds) was added to Moment.js in version 2.8.4. This also adds it to Moment.php's `Moment\CustomFormats\MomentJS` custom format class as well as to its `nl_NL` locale.
See:
- Commit that added it to Moment.js: https://github.com/moment/moment/commit/14f66816c9a88f1c7b387b53ecab92c2ad3d138f
- Moment.js documentation: http://momentjs.com/docs/#/displaying/format/
=> Implements the LTS Moment.js localized format.

src/Moment.php
[DateTime::setTimeZone takes a DateTimeZone object as a parameter](http://php.net/manual/en/datetime.settimezone.php). Moment only takes a string, breaking compatibility when trying to replace use of DateTime with Moment.
=> Moment::setTimeZone is incompatible with DateTime::setTimeZome

src/MomentLocale.php, tests/unit/Moment/MomentGermanLocaleTest.php
Closes #93
Prevent `MomentException` if "f" format is used with locale without "monthsNominative" definition.
=> Fall back missing "monthsNominative" definition to "months"

src/Locales/fr_FR.php
Ordinal seems to not be working, because of the strict condition `$number === 1` while `$number` is actually passed as a `string` added an `OR` case where `$number === '1'` so `$number` can be a string too
=> fix - fr_FR ordinal not working

src/Locales/ca_ES.php
Some breaking errors fixed:
- Typo in ordinals function ($ouput should be $output).
- Wrong order in weekdays and weekdaysShort (arrays should begin with "dilluns" ("Monday").
Improvement:
- Time format: in Catalan, "." is better than ":" as a separator between hours and minutes. Also, suffix " h" is added. When the time was 1.00, the wrong article was being used because the identical comparison was not working.
=> Fix several errors in ca_ES.php

src/Locales/es_ES.php
Identical comparison with getHour was not working, so times such as "1:00" were being preceded by the plural "las" instead the proper singular form "la".
Also, for the type of written language used in the calendar output, not leading zeroes ("G" instead of "H") and " h" suffix is more suitable.
=> Fix time format in es_ES.php

src/Locales/fr_FR.php
Proper time format in French is, for example: "9 h 30" (09:30), that is, no leading zeroes in hours and " h " as a separator.
=> Fix time format in fr_FR

src/Locales/de_DE.php
Added common " Uhr" suffix to german time format.
=> Improved time format in de_DE.php

src/Locales/it_IT.php
Removed leading zeroes in hours of the Italian time format.
=> Improved time format in it_IT.php

.travis.yml, composer.json, tests/build.xml, tests/unit/Moment/MomentLatvianLocaleTest.php
- Use the class-based PHPUnit namespace.
- Set the multiple PHPUnit version for the different PHP versions tests.
- Add the ```nightly``` test and that can be failed during Travis CI build.
- Add the ```php-7.2``` tests in Travis CI build setting.
=> Test enhancement

src/Moment.php
Fix `Moment::createFromFormat` declaration to be compatible with php < 7.2.  `DateTimeZone` typehint was added in 9d1011ca3836766237cf92a7f8cf9274ad44fa9c to improve phpdoc.
closes #170
```
There was 1 error:
1) Moment\MomentBritishEnglishLocaleTest::testWeekdayNames
Declaration of Moment\Moment::createFromFormat($format, $time, ?DateTimeZone $timezone = NULL, ?Moment\FormatsInterface $formatsInterface = NULL) should be compatible with DateTime::createFromFormat($format, $time, $object = NULL)
/home/travis/build/fightbulc/moment.php/src/Moment.php:1428
/home/travis/build/fightbulc/moment.php/tests/unit/Moment/MomentBritishEnglishLocaleTest.php:15
```
=> Remove typehint to fix php < 7.2 compatibility

src/Locales/nl_NL.php
the `L` and `l` formats were incorrectly formatted in dutch, transferred this to the correct formatting.
=> fixed the dutch l and L date formats

src/Moment.php
Make any functions that can be called through implicitCloning() protected so subclasses don't crash accessing private functions.
This came about due to me making a "MomentImmutable" subclass that acts like DateTimeImmutable.  If you want, I can submit this as a PR too.
=> Prevent crashes if overriding class and accessing implicitCloning functions

src/Moment.php
Follow up to #123, if an invalid value is passed in, Moment::createFromFormat should return FALSE, as DateTime::createFromFormat does, instead of throwing a TypeError from passing false to Moment::fromDateTime.
=> Match signature for DateTime::createFromFormat and return FALSE on failure

tests/unit/Moment/MomentCanadianEnglishLocaleTest.php, tests/unit/Moment/MomentCanadianFrenchLocaleTest.php
Just fixing typo of "Candian" 🇨🇦 tests
=> Fix test classes naming typo

.github/workflows/php.yml, src/Moment.php, tests/build.xml, tests/unit/Moment/MomentBritishEnglishLocaleTest.php, tests/unit/Moment/MomentCanadianEnglishLocaleTest.php, tests/unit/Moment/MomentCanadianFrenchLocaleTest.php, tests/unit/Moment/MomentEsperantoLocaleTest.php, tests/unit/Moment/MomentFrenchLocaleTest.php, tests/unit/Moment/MomentGermanLocaleTest.php, tests/unit/Moment/MomentLatvianLocaleTest.php, tests/unit/Moment/MomentPolishLocaleTest.php, tests/unit/Moment/MomentRussianLocaleTest.php, tests/unit/Moment/MomentSimilarLocaleTest.php, tests/unit/Moment/MomentTurkishLocaleTest.php, tests/unit/Moment/MomentUkrainianLocaleTest.php
chore: define return type for locale test scripts method `setUp(): void`
chore: migrated PHPUnit configuration using `--migrate-configuration`
fix: suppress deprecation warnings generated in PHP 8.1 with `#[\ReturnTypeWillChange]`
chore: remove unsupported PHP versions
fixes #210 #207
=> fix: PHP 8.1 deprecation warnings

tests/phpunit.xml
=> Fix: Disable result cache

tests/Unit/MomentTest.php
This pull request
Related to #214.
=> Fix: Add tests to assert compatibility with PHP 8.1
