src/Locales/zh_CN.php
I have tested this, and it worked well.
=> Fix locale zh_CN with php's datetime token

src/Locales/cs_CZ.php, tests/cs_CZ.php
hi, I tried to handle the different grammatical cases Czech language needs for relative future and past times by assigning a function ['relativeTime'][various_keys] but the args I got are not much helpful - so I opted for word forms that should be suitable for the past variant (which seems more used to me)
=> initial Czech locales

src/Locales/it_IT.php
otherwise explode will throw this warning:
```
PHP Warning:  explode(): Empty delimiter in vendor/fightbulc/moment/src/Locales/it_IT.php on line 7
PHP Warning:  explode(): Empty delimiter in vendor/fightbulc/moment/src/Locales/it_IT.php on line 8
PHP Warning:  explode(): Empty delimiter in vendor/fightbulc/moment/src/Locales/it_IT.php on line 9
PHP Warning:  explode(): Empty delimiter in vendor/fightbulc/moment/src/Locales/it_IT.php on line 10
```
=> adding delimiter character to italian locale

src/Locales/da_DK.php
This PR adds Danish strings for moment.php.
=> Add Danish localization

src/Locales/nl_NL.php
Oops! Didn't see the typo there.
=> Typo in Dutch locale

src/Locales/id_ID.php
I just added Indonesian Translation for moment.php
=> Added Indonesian Translation

src/Locales/pl_PL.php, tests/unit/Moment/MomentPolishLocaleTest.php
Hi,
I've created Polish translation. I will be glad if You merge it to master, because I would like to use Your great library in my another project. Good job man!
=> Added Polish translation

src/Locales/zh_CN.php, src/Locales/zh_TW.php
Fix Chinese weekday wording,
Monday is `周一`,
and Sunday is `周日`.
=> fix chinese weekday translation

src/Moment.php, tests/unit/Moment/MomentTest.php
Fixed the calculation of seconds, using internal days to make it work with leap years.
=> Fixed the calculation of seconds

README.md, src/Locales/vi_VN.php
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A
=> Add locale file for vi_VN

src/Locales/oc_lnc
=> Occitan version

src/Locales/oc_LNC.php
Now it's should be perfect :)
If you wonder about Occitan, compare it to ca_ES, its sister language ;)
=> Occitan version update

src/Locales/hu_HU.php
Based on https://github.com/moment/moment/blob/4b3fc58/src/locale/hu.js
=> Add Hungarian locale

src/Locales/uk_UA.php, tests/unit/Moment/MomentUkrainianLocaleTest.php
=> Ukrainian locale and tests

src/Locales/tr_TR.php, tests/unit/Moment/MomentTurkishLocaleTest.php
Hi dudes,
Simply, this PR includes Turkish locale  config and unit test routines.
=> Turkish language support and unit tests

src/Locales/ru_RU.php, tests/unit/Moment/MomentRussianLocaleTest.php
`future` string see https://github.com/moment/moment/blob/develop/locale/ru.js#L130
=> Fix russian locale

src/Locales/fr_FR.php
=> ref #106 : typo in french translation

src/Locales/ru_RU.php, tests/unit/Moment/MomentRussianLocaleTest.php
fix https://github.com/fightbulc/moment.php/issues/68#issuecomment-264890181
=> fix ordinal suffixes for ru_RU

.travis.yml, README.md, src/Locales/lv_LV.php, tests/unit/Moment/MomentLatvianLocaleTest.php
Greetings.
- Implemented locale for Lavia
- Added tests in the same style
=> Implemented lv_LV locale

src/Locales/lv_LV.php, tests/unit/Moment/MomentLatvianLocaleTest.php
Greetings.
Added missing the locale index key for Latvian locale as was mentioned in [Pull request 128](https://github.com/fightbulc/moment.php/pull/128)
KR.
=> Added missing the locale index key for Latvian locale

src/Locales/en_GB.php, src/Locales/lv_LV.php, src/Locales/ru_RU.php, src/MomentFromVo.php, tests/unit/Moment/MomentBritishEnglishLocaleTest.php, tests/unit/Moment/MomentLatvianLocaleTest.php, tests/unit/Moment/MomentRussianLocaleTest.php
=> fixes to getRelative

src/Locales/en_US.php, src/Moment.php, src/MomentLocale.php, tests/test.html, tests/test.php
* Added fallback option for similar locale (`en` falls back to `en_US`);
* Added custom MomentJS formats for `en_US`;
=> Fallback for similar locale & added custom formats for en_US

src/MomentFromVo.php, tests/unit/Moment/MomentLatvianLocaleTest.php
=> Avoid rounding errors in getRelative()

README.md
Just to have nicer README.md :)
=> Fix some text indentations in README.md

src/Locales/kz_KZ.php
I am add an Kazakh language locale.
=> add Kazakh locale.

src/Locales/eo.php, tests/unit/Moment/MomentEsperantoLocaleTest.php
Hi, here's a file adding support for Esperanto based on what was already done for MomentJS https://github.com/moment/moment/blob/develop/src/locale/eo.js
=> Add Esperanto locale

src/Locales/fr_CA.php, tests/unit/Moment/MomentCanadianFrenchLocaleTest.php
[See here Moment.js fr-ca locale](https://github.com/moment/moment/blob/develop/src/locale/fr-ca.js)
=> Adjust fr_CA short month names and short week days to match those of Moment.js

.github/workflows/php.yml
This pull request
💁‍♂️ For reference, see https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs.
=> Enhancement: Use matrix strategy

.github/workflows/php.yml, README.md
=> Enhancement: Add support for PHP 8.2

.github/workflows/integrate.yaml
=> Enhancement: Run tests on PHP 7.3

.github/workflows/integrate.yaml
=> Enhancement: Run tests on PHP 7.2

.github/workflows/integrate.yaml
=> Enhancement: Run tests on PHP 7.1

.github/workflows/integrate.yaml
=> Enhancement: Enable required extensions only

.github/workflows/integrate.yaml, README.md
=> Enhancement: Add support for PHP 8.3
